### ISSUE TITLE
attribute 'agenixRoot' missing

### ISSUE THREAD

**Issue by MidAutumnMoon** [ryantm/agenix#54] opened 2021-09-09 04:17 UTC
After a recent update of nixpkgs unstable, the system rebuild fails with this error message "attribute 'agenixRoot' missing".

I found this pull request https://github.com/NixOS/nixpkgs/pull/136605 has changes to users/groups and system activation scripts, but sadly I can't quite understand how does the activation process of NixOS work.

Hope you can have a look of it :)

**Comment by MatthewCroughan** [comment] 2021-09-09 22:46
The error looks like this:
```
[root@swordfish:/etc/nixos]# nixos-rebuild switch -L
building the system configuration...
error: attribute 'agenixRoot' missing

       at /nix/store/6dcqil119qr3sad2lp9ykkkc852ppmqm-source/lib/strings-with-deps.nix:72:71:

           71|           else if done ? ${entry} then f done (tail todo)
           72|           else f (done // listToAttrs [{name = entry; value = 1;}]) ([predefined.${entry}] ++ tail todo);
             |                                                                       ^
           73|     in (f {} arg).result;
(use '--show-trace' to show detailed location information)
```

**Comment by ryantm** [comment] 2021-09-10 17:56
Since we're leaving this one open. Here's the workaround for now copied from #55:

```nix
system.activationScripts.users.supportsDryActivation = lib.mkForce false;
```

**Comment by ryantm** [comment] 2021-09-10 18:24
I'd appreciate it if people could test #57 without the above workaround. If it works for you, I'll merge it then we don't have to be bothering people with this issue while we fix it properly.

**Comment by legendofmiracles** [comment] 2021-09-10 20:11
I don't think that it fixes it, I cloned the rope, checked out into the PR and changed my input url; but the error still pops up

**Comment by ryantm** [comment] 2021-09-10 23:32
@legendofmiracles Thanks for testing. The issue serves as a continual reminder to never use `//`. I believe it works now. I wasn't able to set supportsDryActivation to false for the specialfs activation script because it isn't using the attrset options.

Seems to work for me now, but would someone like to try again as a sanity check?

**Comment by legendofmiracles** [comment] 2021-09-11 01:01
Yup that works for me as well!

**Comment by ryantm** [comment] 2021-09-11 02:04
Thanks! This is resolved now.

**Comment by MidAutumnMoon** [comment] 2021-09-11 10:42
Thanks! My workaround is to add `supportsDryActivation` attribute to agenix and it also works fine.

**Comment by ryantm** [comment] 2021-09-11 12:08
> Thanks! My workaround is to add `supportsDryActivation` attribute to agenix and it also works fine.

@MidAutumnMoon Doing that is going to decrypt the secrets and install them during dry activation, right? Unless you also implemented the dry activation logic.

**Comment by nrdxp** [comment] 2021-09-11 18:51
@ryantm this issue seems to have resurfaced with the most recent version of nixos-unstable branch. your workaround still works though.

**Comment by ryantm** [comment] 2021-09-11 20:38
@nrdxp are you saying using latest agenix master and nicos-unstable still has the issue?

**Comment by nrdxp** [comment] 2021-09-11 21:04
yes I just bumped my nixos-unstable input in my systems flake, and agenix as well just to be sure and I got this exact error. Using your workaround listed above resolved it though.

**Comment by legendofmiracles** [comment] 2021-09-11 21:20
@nrdxp I cannot reproduce that 😕

**Comment by nrdxp** [comment] 2021-09-11 21:48
This was also reported by @Princemachiavelli a few days ago on Matrix, so at least it is not just me. Perhaps it depends on something else though as we are both DevOS users.

**Comment by MidAutumnMoon** [comment] 2021-09-12 02:35
> > Thanks! My workaround is to add `supportsDryActivation` attribute to agenix and it also works fine.
> 
> @MidAutumnMoon Doing that is going to decrypt the secrets and install them during dry activation, right? Unless you also implemented the dry activation logic.

Yes, this method is not that "dry", but not a big problem, I think.

**Comment by ryantm** [comment] 2021-09-16 17:33
@nrdxp This should be fixed now because of https://github.com/NixOS/nixpkgs/pull/137508 Could you please confirm?

**Comment by nrdxp** [comment] 2021-09-16 17:48
I'll test as soon as I can, I had a drive failure last week and still haven't had time to redeploy my config to the affected machine.

**Comment by ryantm** [comment] 2021-09-17 16:31
I think it is fixed, feel free to post if you still have trouble.

**Closed** 2021-09-17 16:31 UTC
